### ISSUE TITLE
issue with minishift start

### ISSUE THREAD

**Issue by fmontaldo** [itikabc/minishift#1]
Hi,

I just discoverd your youtube channel and is amazing. Can I ask you some questions regarding minishift instalation?.

**Comment by lenocruz** [comment]
Minishift is not really like the openshift.  You should install the one that gshipley put it on the youtube/openshift (or use the make gcc source code), maybe it will really work if you have 32G ram like he advised.  But anyway shoot your question.

**Comment by fmontaldo** [comment]
Hi

Thanks for your reply. I tough it can be run with 20 Gb and 2 Gb and I can
run it my personal laptop. I got a documentation regarding the installation
of openshift origin in centos 7 but I don't understand the configuration of
the network inside the opneshift. Can I pass you the document so you can
guide me?. Maybe this experience will help others I can document and sent
it to the community.

Regards

2018-02-24 16:19 GMT-03:00 itikabc <notifications@github.com>:
